version: '3.1'

services:
  web:
    container_name: orwkig_web
    build: ./mylist.webapp 
    ports:
      - "3001:3000"
    
  api:
    container_name: orwkig_api
    build: ./API 
    ports:
      - "5000:80"
    depends_on: 
      - postgres

  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: orwkig_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports: 
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      
  prometheus:
    container_name: orwkig_prometheus
    build: 
      context: .
      dockerfile: dockerfile-prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    container_name: orwkig_grafana
    image: grafana/grafana-enterprise
    ports:
      - "3002:3000"   
    depends_on:
      - prometheus

  loki:
    container_name: orwkig_loki
    image: grafana/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml


volumes:
  postgres:
    driver: local

