{
 "title": "Dashboard",
 "description": "MyList Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ListController", "label": "Controller", "query": { "query": "label_values(controller)" } }
  ]
 },
 "panels": [
  {
   "title": "Increase of request per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_requests_received_total{code=~\"2\\\\d\\\\d\"}[10m])",
     "legendFormat": "{{method}}, /{{endpoint}}"
    }
   ]
  },
  {
   "title": "Logs when start command",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"web_app\"} |= `{\"Message\":\"Start `"
    }
   ]
  },
  {
   "title": "10 top products order by CreatedOn",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * \r\nFROM \"Products\" \r\norder by \"CreatedOn\"\r\ndesc\r\nlimit 10"
    }
   ]
  },
  {
   "title": "Errors per endpoint per day",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_received_total{code=~\"4\\\\d\\\\d|5\\\\d\\\\d\"}",
     "legendFormat": "{{method}}, /{{endpoint}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(system_runtime_cpu_usage[30s]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}